from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Suitability debate state (Advocate vs Skeptic)
class SuitabilityDebateState(TypedDict):
    advocate_history: Annotated[str, "Advocate's argument history"]
    skeptic_history: Annotated[str, "Skeptic's argument history"]
    history: Annotated[str, "Full conversation history"]
    current_response: Annotated[str, "Latest response"]
    judge_decision: Annotated[str, "Evaluation Manager's decision"]
    count: Annotated[int, "Debate turn count"]


# Risk debate state (Brand Safety / ROI Risk / Audience Fit)
class RiskDebateState(TypedDict):
    brand_safety_history: Annotated[str, "Brand Safety Analyst's history"]
    roi_risk_history: Annotated[str, "ROI Risk Analyst's history"]
    audience_fit_history: Annotated[str, "Audience Fit Analyst's history"]
    history: Annotated[str, "Full conversation history"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_brand_safety_response: Annotated[str, "Latest Brand Safety response"]
    current_roi_risk_response: Annotated[str, "Latest ROI Risk response"]
    current_audience_fit_response: Annotated[str, "Latest Audience Fit response"]
    judge_decision: Annotated[str, "Campaign Manager's decision"]
    count: Annotated[int, "Discussion turn count"]


class AgentState(MessagesState):
    # Input
    influencer_username: Annotated[str, "TikTok username to analyze"]
    analysis_date: Annotated[str, "Date of analysis"]
    target_market: Annotated[str, "Target market code (MY, PH, VN, BR)"]

    sender: Annotated[str, "Agent that sent this message"]

    # Analyst reports
    metrics_report: Annotated[str, "Report from the Metrics Analyst"]
    content_report: Annotated[str, "Report from the Content Analyst"]
    audience_report: Annotated[str, "Report from the Audience Analyst"]
    commerce_report: Annotated[str, "Report from the Commerce Analyst"]

    # Suitability debate
    suitability_debate_state: Annotated[
        SuitabilityDebateState, "Current state of the suitability debate"
    ]
    evaluation_plan: Annotated[str, "Plan generated by the Evaluation Manager"]

    # Partnership strategy
    strategist_partnership_plan: Annotated[str, "Plan from the Partnership Strategist"]

    # Risk debate
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the risk debate"
    ]
    final_assessment: Annotated[str, "Final assessment from Campaign Manager"]
